-- V13__email_verification_username_and_tokens.sql
-- Email verification gating, unique usernames, and the token table that
-- backs both verification and password reset.
--
-- ============================================================
-- 1. is_verified: REUSED, not re-added
-- ============================================================
-- V1 already created users.is_verified, and User.java already maps it —
-- but nothing has ever read or written it (confirmed: the only references
-- are the field and its accessors). It means exactly what verification
-- gating needs, so this reuses it rather than adding an email_verified
-- column beside it. Two columns meaning "is this email confirmed" is how
-- you get a login path checking the wrong one a year from now.
--
-- Note it is NOT the same thing as is_active, which UserPrincipal maps to
-- isEnabled() and the JWT filter already enforces. Verified means "proved
-- they own the address"; active means "not banned". Keep them separate.
--
-- BACKFILL IS LOAD-BEARING: every existing user is marked verified before
-- the NOT NULL lands. Login gating ships in the same release, so without
-- this line every current account is locked out the moment it deploys —
-- they never had a chance to click a link that did not exist yet.

UPDATE users SET is_verified = TRUE WHERE is_verified IS NULL OR is_verified = FALSE;

ALTER TABLE users ALTER COLUMN is_verified SET NOT NULL;
ALTER TABLE users ALTER COLUMN is_verified SET DEFAULT FALSE;

-- Existing rows kept TRUE above; the DEFAULT applies to rows inserted from
-- here on, which must verify. The entity sets this explicitly on register,
-- so the default is a backstop for any path that forgets.

-- ============================================================
-- 2. username
-- ============================================================
-- Added nullable, backfilled, then constrained — the only order that works
-- on a table with existing rows.
--
-- Stored already-lowercased so a plain UNIQUE constraint gives
-- case-insensitive uniqueness without a functional index (Hibernate's
-- ddl-auto: validate does not inspect functional indexes, so a plain
-- constraint keeps the schema and the entity honest with each other).
-- The service lowercases on input to match.

ALTER TABLE users ADD COLUMN username VARCHAR(30);

-- Derive from the email local part: strip anything not [a-z0-9_], cap at
-- 24 chars to leave room for a collision suffix, and fall back to 'user'
-- for an address whose local part is entirely punctuation.
WITH base AS (
    SELECT id,
           COALESCE(
               NULLIF(left(regexp_replace(lower(split_part(email, '@', 1)),
                                          '[^a-z0-9_]', '', 'g'), 24), ''),
               'user'
           ) AS stem
    FROM users
),
numbered AS (
    SELECT id, stem,
           ROW_NUMBER() OVER (PARTITION BY stem ORDER BY id) AS rn
    FROM base
)
UPDATE users u
SET username = CASE WHEN n.rn = 1 THEN n.stem
                    ELSE n.stem || n.rn::text END
FROM numbered n
WHERE u.id = n.id;

ALTER TABLE users ALTER COLUMN username SET NOT NULL;
ALTER TABLE users ADD CONSTRAINT uq_users_username UNIQUE (username);

-- ============================================================
-- 3. user_tokens
-- ============================================================
-- ONE table for both verification and reset, discriminated by purpose.
-- The two are mechanically identical — issue a single-use secret, hash it
-- at rest, expire it, consume it once — and splitting them would mean two
-- entities, two repositories, and two services differing only in a string.
-- Same storage design as refresh_tokens (V5): the raw UUID goes to the
-- user in an email and is never stored; only its SHA-256 hex digest lands
-- here, so a leaked database dump cannot be replayed into a password reset.
--
-- consumed_at rather than deleting the row: a reset link clicked twice
-- should say "already used", which needs the row to still exist. It is
-- also the audit trail for "when was this account's password last reset".

CREATE TABLE public.user_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT                              NOT NULL,
    purpose     VARCHAR(32)                         NOT NULL,
    token_hash  VARCHAR(64)                         NOT NULL,
    issued_at   TIMESTAMP(6) WITHOUT TIME ZONE      NOT NULL DEFAULT now(),
    expires_at  TIMESTAMP(6) WITHOUT TIME ZONE      NOT NULL,
    consumed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT fk_ut_user FOREIGN KEY (user_id)
        REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT user_tokens_purpose_check
        CHECK (purpose IN ('EMAIL_VERIFICATION', 'PASSWORD_RESET'))
);

CREATE UNIQUE INDEX uq_user_tokens_hash ON public.user_tokens (token_hash);

-- Lookup pattern is "newest unconsumed token for this user and purpose",
-- used when re-sending a verification email and when invalidating a user's
-- outstanding reset links after a successful reset.
CREATE INDEX idx_user_tokens_user_purpose ON public.user_tokens (user_id, purpose);
