-- V14__category_tree_handmade_and_tags.sql
-- Categories move from a Java enum to a table, "handmade" becomes a flag
-- instead of a category, and products gain free-form tags.
--
-- ============================================================
-- WHY A TABLE
-- ============================================================
-- V10 put five categories in an enum with a CHECK constraint, and wrote
-- down the cost itself: "If ProductCategory ever gains a value, the enum
-- AND a follow-up migration updating this CHECK must change together."
-- Every vendor asking for a new category was a code change, a migration,
-- a redeploy, and a matching edit to the frontend's data/categories.ts.
-- A table makes that an admin insert.
--
-- ============================================================
-- WHY HANDMADE IS NOT A CATEGORY
-- ============================================================
-- With CRAFTS as a category, a handmade beaded necklace had to be either
-- Crafts or Fashion>Jewellery, and the vendor had to guess. Shoppers
-- looking for a necklace browse Jewellery; shoppers who care about
-- handmade want it across the whole catalogue. Category answers "what is
-- it", handmade answers "how was it made" — independent questions, so
-- independent fields.
--
-- Existing CRAFTS products are therefore migrated to Art and crafts AND
-- flagged handmade. That is the honest reading of what the vendor meant
-- when they picked CRAFTS, and it is the one mapping in this migration
-- that is a judgement call rather than a rename.

-- ============================================================
-- 1. categories
-- ============================================================
-- Two levels only, enforced by the CHECK below: a subcategory's parent
-- must itself be top-level. Arbitrary depth sounds free but is not — the
-- chip row, the breadcrumb, and the "count everything beneath me" query
-- all get materially harder, and nobody has asked for Produce > Fruit >
-- Citrus. This constraint is cheap to drop later and expensive to have
-- omitted, because by then there is depth-3 data to clean up.
--
-- NOTE: no product_count column. The spec called for one, denormalised
-- and refreshed on write. Deferred deliberately — see the comment on the
-- count query in CategoryService. Adding it later is one migration and
-- does not change the API shape.

-- Depth is enforced declaratively, with no trigger and no subquery (a CHECK
-- cannot contain one — Postgres rejects it outright). The trick:
--
--   depth        is 0 for a root, 1 for a child.
--   parent_depth is NULL for a root, and always literally 0 for a child.
--   the FK points (parent_id, parent_depth) at (id, depth).
--
-- So a child can only reference a parent whose depth is 0, i.e. a root.
-- A grandchild would need its parent to have depth 0, but any row with a
-- parent has depth 1, so the reference cannot resolve and the insert
-- fails. Both columns are GENERATED, so neither the app nor an admin can
-- put them out of step with parent_id.
--
-- Composite FKs default to MATCH SIMPLE: a row with any NULL in the
-- referencing columns satisfies it. That is exactly what lets roots
-- (parent_depth NULL) sit in the same table without a second constraint.

CREATE TABLE public.categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   BIGINT      NULL,
    name        VARCHAR(80) NOT NULL,
    slug        VARCHAR(80) NOT NULL,
    icon        VARCHAR(16) NULL,
    sort_order  INT         NOT NULL DEFAULT 0,
    active      BOOLEAN     NOT NULL DEFAULT TRUE,

    depth        SMALLINT GENERATED ALWAYS AS
                 (CASE WHEN parent_id IS NULL THEN 0 ELSE 1 END) STORED,
    parent_depth SMALLINT GENERATED ALWAYS AS
                 (CASE WHEN parent_id IS NULL THEN NULL ELSE 0 END) STORED,

    CONSTRAINT uq_categories_slug     UNIQUE (slug),
    CONSTRAINT uq_categories_id_depth UNIQUE (id, depth),
    CONSTRAINT categories_no_self_parent CHECK (parent_id IS NULL OR parent_id <> id),
    CONSTRAINT fk_category_parent_is_top FOREIGN KEY (parent_id, parent_depth)
        REFERENCES public.categories (id, depth) ON DELETE RESTRICT
);

-- ON DELETE RESTRICT, not CASCADE: deleting Fashion should not silently
-- take seven subcategories and orphan every product under them. Deleting
-- a category with children must be a deliberate two-step.

CREATE INDEX idx_categories_parent ON public.categories (parent_id);

-- ============================================================
-- 2. Seed the taxonomy
-- ============================================================
-- sort_order is explicit rather than alphabetical: Produce and Pantry lead
-- because this is a food-first local marketplace, and Other is last
-- because a catch-all should never be the easy click.

INSERT INTO public.categories (parent_id, name, slug, icon, sort_order) VALUES
    (NULL, 'Produce',                  'produce',                  '🥑', 10),
    (NULL, 'Pantry',                   'pantry',                   '🍯', 20),
    (NULL, 'Fashion',                  'fashion',                  '👗', 30),
    (NULL, 'Beauty and personal care', 'beauty-and-personal-care', '💄', 40),
    (NULL, 'Home and living',          'home-and-living',          '🛋️', 50),
    (NULL, 'Art and crafts',           'art-and-crafts',           '🎨', 60),
    (NULL, 'Kids and baby',            'kids-and-baby',            '🧸', 70),
    (NULL, 'Other',                    'other',                    '📦', 999);

INSERT INTO public.categories (parent_id, name, slug, icon, sort_order)
SELECT p.id, c.name, c.slug, NULL, c.sort_order
FROM (VALUES
    ('produce',                  'Fruit and veg',              'fruit-and-veg',              10),
    ('produce',                  'Meat and poultry',           'meat-and-poultry',           20),
    ('produce',                  'Dairy and eggs',             'dairy-and-eggs',             30),
    ('produce',                  'Herbs and plants',           'herbs-and-plants',           40),

    ('pantry',                   'Baked goods',                'baked-goods',                10),
    ('pantry',                   'Preserves and honey',        'preserves-and-honey',        20),
    ('pantry',                   'Snacks',                     'snacks',                     30),
    ('pantry',                   'Spices and condiments',      'spices-and-condiments',      40),
    ('pantry',                   'Beverages',                  'beverages',                  50),

    ('fashion',                  'Women''s clothing',          'womens-clothing',            10),
    ('fashion',                  'Men''s clothing',            'mens-clothing',              20),
    ('fashion',                  'Kids'' clothing',            'kids-clothing',              30),
    ('fashion',                  'Shoes',                      'shoes',                      40),
    ('fashion',                  'Bags',                       'bags',                       50),
    ('fashion',                  'Jewellery',                  'jewellery',                  60),
    ('fashion',                  'Accessories and sunglasses', 'accessories-and-sunglasses', 70),

    ('beauty-and-personal-care', 'Make-up',                    'make-up',                    10),
    ('beauty-and-personal-care', 'Skincare',                   'skincare',                   20),
    ('beauty-and-personal-care', 'Hair care',                  'hair-care',                  30),
    ('beauty-and-personal-care', 'Fragrance',                  'fragrance',                  40),
    ('beauty-and-personal-care', 'Bath and body',              'bath-and-body',              50),

    ('home-and-living',          'Kitchen and dining',         'kitchen-and-dining',         10),
    ('home-and-living',          'Decor',                      'decor',                      20),
    ('home-and-living',          'Furniture',                  'furniture',                  30),
    ('home-and-living',          'Textiles',                   'textiles',                   40),
    ('home-and-living',          'Garden and outdoor',         'garden-and-outdoor',         50),

    ('art-and-crafts',           'Art and prints',             'art-and-prints',             10),
    ('art-and-crafts',           'Ceramics',                   'ceramics',                   20),
    ('art-and-crafts',           'Stationery and paper',       'stationery-and-paper',       30),
    ('art-and-crafts',           'Craft supplies',             'craft-supplies',             40),

    ('kids-and-baby',            'Toys',                       'toys',                       10),
    ('kids-and-baby',            'Baby gear',                  'baby-gear',                  20),
    ('kids-and-baby',            'Nursery',                    'nursery',                    30)
) AS c(parent_slug, name, slug, sort_order)
JOIN public.categories p ON p.slug = c.parent_slug AND p.parent_id IS NULL;

-- ============================================================
-- 3. products: category_id, handmade, tags
-- ============================================================

ALTER TABLE products ADD COLUMN category_id BIGINT NULL;
ALTER TABLE products ADD COLUMN handmade    BOOLEAN NOT NULL DEFAULT FALSE;

-- TEXT[] rather than a product_tags join table. Tags are read with the
-- product, never independently, and are always replaced wholesale on edit
-- — the two things that make a join table worth its cost (querying tags on
-- their own, mutating one at a time) do not apply. GIN indexed so
-- "products having tag X" stays an index scan.
ALTER TABLE products ADD COLUMN tags TEXT[] NOT NULL DEFAULT '{}';

CREATE INDEX idx_products_tags ON products USING GIN (tags);

-- Map the five old enum values onto the new tree. Everything lands on a
-- TOP-LEVEL category: the old data has no information about which
-- subcategory a product belongs in, and guessing would be worse than
-- leaving vendors to refine it themselves.
UPDATE products p SET category_id = c.id
FROM public.categories c
WHERE c.parent_id IS NULL
  AND c.slug = CASE p.category
      WHEN 'PRODUCE' THEN 'produce'
      WHEN 'PANTRY'  THEN 'pantry'
      WHEN 'CRAFTS'  THEN 'art-and-crafts'
      WHEN 'HOME'    THEN 'home-and-living'
      ELSE 'other'
  END;

-- The judgement call flagged at the top: picking CRAFTS was a vendor
-- saying "I made this", so that intent is preserved as the flag rather
-- than dropped on the floor when the category is renamed.
UPDATE products SET handmade = TRUE WHERE category = 'CRAFTS';

-- Safety net. If any row failed to map, the NOT NULL below would fail with
-- a constraint error naming a column, not a cause. This fails with the
-- reason instead.
DO $$
DECLARE unmapped INT;
BEGIN
    SELECT COUNT(*) INTO unmapped FROM products WHERE category_id IS NULL;
    IF unmapped > 0 THEN
        RAISE EXCEPTION 'V14: % product(s) did not map to a category', unmapped;
    END IF;
END $$;

ALTER TABLE products ALTER COLUMN category_id SET NOT NULL;
ALTER TABLE products ADD CONSTRAINT fk_product_category
    FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE RESTRICT;

-- Replaces idx_products_category_live from V10, same shape and purpose.
CREATE INDEX idx_products_category_id_live ON products (category_id)
    WHERE deleted_at IS NULL;
DROP INDEX IF EXISTS idx_products_category_live;

-- Partial index for the handmade filter chip, matching the live-catalogue
-- pattern above: only TRUE rows are ever filtered on, so only they are
-- worth indexing.
CREATE INDEX idx_products_handmade_live ON products (handmade)
    WHERE deleted_at IS NULL AND handmade = TRUE;

-- ============================================================
-- 4. Drop the old enum column
-- ============================================================
-- Dropped, not left behind. V12 left dead shipping columns in place and
-- had to write a comment explaining they were dead; two columns answering
-- "what category is this" is exactly the ambiguity that costs an afternoon
-- later. The data is fully carried over above, and the check above proves
-- it before this runs.
--
-- Rollback note: reverting past V14 needs a restore, since the enum values
-- only exist in this file after it runs.

ALTER TABLE products DROP CONSTRAINT IF EXISTS products_category_check;
ALTER TABLE products DROP COLUMN category;
