-- V2: append-only audit trail for order status transitions.
--
-- Adaptation notes applied vs V1:
--   V1 uses bigint + separate sequences (decomposed bigserial); V2 uses
--   GENERATED BY DEFAULT AS IDENTITY — both satisfy JPA GenerationType.IDENTITY,
--   the difference is cosmetic at the Hibernate level.
--   FK targets confirmed from V1: public.orders(id) and public.users(id).
--   Timestamp type matches V1: timestamp(6) without time zone.
--
-- This table is append-only by application convention: no UPDATE/DELETE path
-- exists in the service layer, and the column layout reflects that (no
-- soft-delete flag, no editable fields).

CREATE TABLE public.order_status_history (
    id           BIGINT                         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT                         NOT NULL,
    from_status  VARCHAR(32),
    to_status    VARCHAR(32)                    NOT NULL,
    changed_by   BIGINT                         NOT NULL,
    note         VARCHAR(500),
    created_at   TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    updated_at   TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT fk_osh_order      FOREIGN KEY (order_id)   REFERENCES public.orders(id),
    CONSTRAINT fk_osh_changed_by FOREIGN KEY (changed_by) REFERENCES public.users(id)
);

-- The one query pattern this table serves: "history of order X, in order".
CREATE INDEX idx_order_status_history_order
    ON public.order_status_history (order_id, created_at);
