-- V5__refresh_tokens.sql
-- Refresh token table for rotate-on-use sessions.
--
-- DESIGN:
-- The raw token (a UUID) is returned to the client exactly once and never
-- stored. Only its SHA-256 hex digest lives here — a stolen DB row cannot
-- be used directly without the hash input. Reuse detection: if a revoked
-- token is presented, revoked_at IS NOT NULL triggers the nuclear option
-- (all sessions for that user are revoked) and the client must re-login.
--
-- expires_at is set at issue time (now + refresh-expiry-seconds config).
-- Expired rows accumulate and can be pruned by a scheduled job; they are
-- harmless (expiry check short-circuits before the revoked_at check).
--
-- ON DELETE CASCADE: deleting a user (future admin action) automatically
-- cleans up all their refresh tokens.

CREATE TABLE public.refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    token_hash  VARCHAR(64)                         NOT NULL,
    issued_at   TIMESTAMP(6) WITHOUT TIME ZONE      NOT NULL DEFAULT now(),
    expires_at  TIMESTAMP(6) WITHOUT TIME ZONE      NOT NULL,
    revoked_at  TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT fk_rt_user FOREIGN KEY (user_id)
        REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uq_refresh_tokens_hash ON public.refresh_tokens (token_hash);
CREATE INDEX idx_refresh_tokens_user      ON public.refresh_tokens (user_id);
