-- V9__views_favorites_popularity.sql
-- Three tables, three different characters:
--   product_views      — append-only EVENT table, first high-write-volume
--                        table in the system; no updates ever, 90-day
--                        retention sweep, user nullable (anonymous counts
--                        for trending, not for recently-viewed)
--   favorites          — explicit signal + user feature; unique constraint
--                        is the double-submit backstop (house pattern)
--   product_popularity — precomputed READ MODEL, rewritten by the hourly
--                        job; never written on a request path

CREATE TABLE product_views (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NULL REFERENCES users (id),      -- NULL = anonymous
    product_id  BIGINT NOT NULL REFERENCES products (id),
    viewed_at   TIMESTAMP NOT NULL DEFAULT now()
);
-- trending window scans: (product, time); recently-viewed: (user, time)
CREATE INDEX idx_views_product_time ON product_views (product_id, viewed_at);
CREATE INDEX idx_views_user_time    ON product_views (user_id, viewed_at DESC)
    WHERE user_id IS NOT NULL;
-- NOTE for the future: at real volume this table wants time-range
-- partitioning (PARTITION BY RANGE (viewed_at)). Not now — the retention
-- sweep keeps it bounded at portfolio scale — but this comment is where
-- the answer lives when someone asks why inserts got slow.

CREATE TABLE favorites (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users (id),
    product_id  BIGINT NOT NULL REFERENCES products (id),
    created_at  TIMESTAMP NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uq_favorites_user_product UNIQUE (user_id, product_id)
);
CREATE INDEX idx_favorites_product ON favorites (product_id);
-- user_id lookups covered by the unique constraint's leading column.

CREATE TABLE product_popularity (
    product_id      BIGINT PRIMARY KEY REFERENCES products (id),
    sales_count     BIGINT       NOT NULL DEFAULT 0,  -- units, PAID/SHIPPED/DELIVERED only
    review_count    BIGINT       NOT NULL DEFAULT 0,
    avg_rating      NUMERIC(3,2) NOT NULL DEFAULT 0,
    weighted_rating NUMERIC(4,3) NOT NULL DEFAULT 0,  -- Bayesian, see job
    views_30d       BIGINT       NOT NULL DEFAULT 0,
    computed_at     TIMESTAMP    NOT NULL
);
