import React, { useId } from 'react'

/**
 * The eRestyu brand mark: a bold serif "e" in paper, on a flame-gradient
 * rounded tile. Same geometry as public/favicon.svg and the brand pack, all
 * generated by brand/tools/build.js; change it there, then copy E_PATH from
 * brand/_site/geometry.json, never edit it by hand.
 *
 * The "e" is an OUTLINE of Georgia Bold, not live text. It used to be a
 * <text> element asking for Georgia, which gave three different logos:
 *  - Windows and macOS drew Georgia, as intended
 *  - Android has no Georgia and substituted another serif
 *  - in dark theme the fill was var(--paper), which is near-black there, so
 *    dark-mode visitors saw a dark "e" on the orange tile (confirmed live,
 *    2026-09-29)
 * As a path with a fixed fill it is the same letter, in the same colour, on
 * every device and in both themes. Traced at the exact size and position the
 * text used, and pixel-compared against it (brand/tools/extract-e.js).
 *
 * Flame, not aloe: the wordmark beside this mark is itself flame-gradient
 * text, and eRestyu's identity color is the warm flame gradient. A monogram
 * in the wordmark's own gradient, of the wordmark's own first letter, reads
 * as one identity, not two.
 *
 * Reads at 24px in the header and 16px as a favicon.
 */
const E_PATH = 'M337.039 318.535L350.102 327.989Q344.086 337.785 335.578 346.465Q327.070 355.145 316.242 361.332L316.242 361.332Q304.727 367.864 292.953 371.215Q281.180 374.567 265.883 374.567L265.883 374.567Q240.445 374.567 221.969 367.348Q203.492 360.129 191.461 347.926L191.461 347.926Q179.430 335.723 173.500 319.137Q167.570 302.551 167.570 283.129L167.570 283.129Q167.570 265.598 174.016 249.528Q180.461 233.457 192.320 220.910L192.320 220.910Q204.008 208.707 221.797 201.145Q239.586 193.582 261.586 193.582L261.586 193.582Q285.648 193.582 301.117 199.426Q316.586 205.270 326.727 215.582L326.727 215.582Q336.523 225.379 340.992 238.699Q345.461 252.020 345.461 266.629L345.461 266.629L345.461 277.801L229.273 277.801Q229.273 313.035 242.852 331.426Q256.430 349.817 285.992 349.817L285.992 349.817Q302.148 349.817 315.039 340.965Q327.930 332.114 337.039 318.535L337.039 318.535ZM229.273 263.364L284.445 262.676Q284.445 252.364 283.414 241.535Q282.383 230.707 279.805 223.832L279.805 223.832Q276.883 215.754 271.813 211.629Q266.742 207.504 259.008 207.504L259.008 207.504Q245.773 207.504 237.867 220.910Q229.961 234.317 229.273 263.364L229.273 263.364Z'

export function LogoMark({ size = 24 }: { size?: number }) {
  // SiteHeader renders this component up to three times at once (desktop,
  // mobile, drawer) — some just CSS-hidden, not unmounted. A hardcoded
  // gradient id would collide across instances (SVG ids are document-global,
  // not scoped to the <svg> that declares them), so the second and third
  // fill="url(#...)" would silently resolve against nothing. useId gives
  // every mounted instance its own id.
  const gradientId = `logoMarkFlame-${useId()}`
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      aria-hidden="true"
      style={{ flexShrink: 0 }}
    >
      <defs>
        <linearGradient id={gradientId} x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stopColor="#FF9A3D" />
          <stop offset="60%" stopColor="#FF4626" />
          <stop offset="100%" stopColor="#E31C3D" />
        </linearGradient>
      </defs>
      <rect width="24" height="24" rx="5.28" fill={`url(#${gradientId})`} />
      {/* The path is in the generator's 512-unit tile; 24 / 512 = 0.046875. */}
      <g transform="scale(0.046875)">
        <path d={E_PATH} fill="#F5F7F3" />
      </g>
    </svg>
  )
}
